# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 655aa1b75ba05131594f6df09c550585031f1f0ab0bbaba6df6d75bebc7b5daf2c6d00089533534bccf84c036650f3856314e47d15e738f20577f9d193df8b6e

test:
  secret_key_base: 4fee1bc1340c81c3f6083855c8e8bf9ce6cfbe74c56c13cbaae919e80e122ab9da3ad61c34208a1bb85a3cfdcd0040eed012ad280138dafe681053c678118dc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
